[project]
name = "uuid"
version = "0.1.0"
description = ""
author = "Ethan Rucar <ethan.rucar@gmail.com>"
license = "MIT"
exclude = [
    "src",
    "target",
    "Cargo.lock",
    "Cargo.toml"
]

[targets]
linux = "libuuid.so"
window = "uuid.dll"
macos = "libuuid.dylib"

[dependencies]